### PR TITLE
formatField fails on number fields, dont attempt to quote non strings

### PR DESCRIPTION
**Pull request by morganrallen**

### CODE REVIEW

**Comment by ahdinosaur** [comment]
hey @morganrallen, thanks for finding a bug and sending a pull request! :smile_cat: 

regarding the bugfix implementation, are you sure we want to return non-strings from the formatter? my intuition tells me a better solution would be to coerce all non-strings into strings with `.toString()`. what are your thoughts on this approach?

**Comment by morganrallen** [comment]
No, I'd want a number to be preserved as a number, if it's coerced, you're changing the meaning of the original value. My thinking is if you were to reverse the operation, it should be the same. If a number is coerced into a String, it will mean loosing if trying to parse it back.

**Comment by morganrallen** [comment]
Further reading.
Value as defined by http://json.org

## value
- string
- number
- object
- array
- true
- false
- null

In my view, handling `Object` and `Array` are out of the scope of `csv-formatter`, the user should clean those up before submitting, but all other primitive should be preserved, and as `String` is the only type needing escaping, all other should be returned untouched.

**Comment by ahdinosaur** [comment]
hmm, i see your point, but this is CSV not JSON. as described in [CSV specification](https://en.wikipedia.org/wiki/Comma-separated_values#Specification), a CSV file is itself a string, which is why i figured everything should be coerced to a string.

also, if we look at https://github.com/holodex/csv-formatter/blob/master/index.js#L48-L54, the output of `formatRow` takes the result of `formatField` and coerces it into a string anyways, so we might as well coerce it early in case the stringified field needs a quote (e.g. this would be the case for `Object` or `Array`, which is yeah not ideal to handle but we should do something that doesn't break your CSV file).

can you explain more your use case where you want everything except strings to remain untouched? i'm unsure what that even means when i understand CSV as an encoded string format for rows of data, as in what does a CSV row with a non-string field even mean?

**Comment by morganrallen** [comment]
I suppose you are right then, if the string isn't being "quoted", then it doesn't actually matter how the string is portrayed. So then... my real concern is simply not running `.indexOf` on non-string, which ever way you want to accomplish works for me.

Thanks a ton @ahdinosaur !

**Comment by morganrallen** [comment]
Max has also updated csv-spectrum with a test that should have caught this.

**Comment by ahdinosaur** [comment]
cool, gonna close this and merge #2 and #3 then. no problem, thank you! :cat:

**Comment by ahdinosaur** [comment]
[tagged](https://github.com/holodex/csv-formatter/releases/tag/1.0.1) and [published](https://www.npmjs.com/package/csv-formatter) as 1.0.1

**Pull request closed without merging**
